use NHAKHOA
go

CREATE OR ALTER PROC SP_INSERT_HOADON
    @IDHOSO VARCHAR(5),
    @IDNVLAP VARCHAR(5)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HoSoBenhNhan WHERE IDHoSo = @IDHOSO)
	BEGIN
        RAISERROR('INVALID HO SO BENH NHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF EXISTS (SELECT * FROM HoaDon WHERE IDHoSo = @IDHOSO)
	BEGIN
        RAISERROR('HO SO BENH NHAN NAY DA CO HOA DON', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @IDNVLAP NOT LIKE 'NV%' AND NOT EXISTS (SELECT * FROM NhanSu
        WHERE IDNhanSu = @IDNVLAP)
	BEGIN
        RAISERROR('INVALID IDNVLAP', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    INSERT INTO HOADON
    VALUES (@IDHOSO, @IDNVLAP, 0) --TONG TIEN BAN DAU SET LA 0
COMMIT TRAN
RETURN 0
GO

EXEC SP_INSERT_HOADON
 'HS01', 'NV01'

EXEC SP_INSERT_HOADON
 'HS03', 'NV01'
SELECT * FROM HoaDon
--delete from HoaDon WHERE IDHoSo = 'HS03'