USE NHAKHOA
GO

CREATE OR ALTER PROC SP_INSERT_HOSOBENHNHAN
	@IDHOSO VARCHAR(5) = NULL,
	@THOIGIANKHAM DATE,
    @IDKHACHHANG VARCHAR(5),
    @IDNHASI VARCHAR(5)    
AS BEGIN TRAN
	IF DATEDIFF(d, @THOIGIANKHAM, GETDATE()) > 0
	BEGIN
        RAISERROR('THOI GIAN KHONG HOP LE', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM KHACHHANG
        WHERE IDKHACHHANG = @IDKHACHHANG) 
	BEGIN
        RAISERROR('INVALID IDKHACHHANG', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM NhanSu WHERE IDNhanSu = @IDNHASI) 
	BEGIN
        RAISERROR('INVALID MANHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF EXISTS (SELECT * FROM HoSoBenhNhan
        WHERE IDBenhNhan = @IDKHACHHANG AND NhaSi = @IDNHASI AND ThoiGianKham = @THOIGIANKHAM) 
	BEGIN
        RAISERROR('HO SO BENH NHAN CHO LAN KHAM NAY DA TON TAI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    SELECT @IDHOSO = IDHOSO FROM HoSoBenhNhan
    WHERE IDHOSO = (SELECT MAX(IDHOSO) FROM HoSoBenhNhan)

    SET @IDHOSO = dbo.F_GenerateID('HS', @IDHOSO)
    
    INSERT INTO HoSoBenhNhan 
	VALUES (@IDHOSO, @THOIGIANKHAM, @IDKHACHHANG, @IDNHASI)
COMMIT TRAN
RETURN 0
GO

EXEC SP_INSERT_HOSOBENHNHAN
 null, N'2024/10/12', 'KH01', 'NS01'

 
EXEC SP_INSERT_HOSOBENHNHAN
 null, N'2024/09/22', 'KH01', 'NS01'

EXEC SP_INSERT_HOSOBENHNHAN
 null, N'2024/11/15', 'KH01', 'NS02'

 EXEC SP_INSERT_HOSOBENHNHAN
 null, N'2024/02/10', 'KH06', 'NS03'

--SELECT * FROM HoSoBenhNhan
--delete FROM HoSoBenhNhan WHERE IDBenhNhan = 'KH06'
--SELECT * FROM LichHen