USE NHAKHOA
GO

CREATE OR ALTER PROC SP_INSERT_SUDUNGTHUOC
    @IDHOSO VARCHAR(10),
    @MATHUOC VARCHAR(5),
    @SOLUONG INT
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HoSoBenhNhan
        WHERE @IDHOSO = IDHoSo)
	BEGIN
        RAISERROR('INVALID HO SO BENH NHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM HoaDon
        WHERE IDHoSo = @IDHOSO)
	BEGIN
        RAISERROR('HO SO CHUA CO HOA DON', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) 
	BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC
        AND SoLuongTon >= @SOLUONG) 
	BEGIN
        RAISERROR('SO LUONG THUOC KHONG DU', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF EXISTS (SELECT * FROM SuDungThuoc
        WHERE @IDHOSO = IDHoSo AND IDThuoc = @MATHUOC) BEGIN
        RAISERROR('THUOC DA DUOC KE', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    DECLARE @TIENTHUOC INT
    SET @TIENTHUOC = (SELECT DonGia FROM THUOC WHERE MATHUOC = @MATHUOC) * @SOLUONG

    INSERT INTO SuDungThuoc
    VALUES (@MATHUOC, @IDHOSO, @SOLUONG)

    UPDATE THUOC SET SoLuongTon = SoLuongTon - @SOLUONG WHERE MATHUOC = @MATHUOC

    UPDATE HoaDon SET TongTien = TongTien + @TIENTHUOC WHERE IDHoSo = @IDHOSO
COMMIT TRAN
RETURN 0
GO

SELECT * FROM HoSoBenhNhan
SELECT * FROM HOADON
SELECT * FROM Thuoc
EXEC SP_INSERT_SUDUNGTHUOC
 'HS01', 'TH01', 6

EXEC SP_INSERT_SUDUNGTHUOC
 'HS03', 'TH06', 10

-- DELETE FROM SuDungThuoc WHERE IDThuoc = 'TH06' AND IDHoSo = 'HS03'
 SELECT * FROM SuDungThuoc