USE NHAKHOA
GO 

CREATE OR ALTER PROC SP_INSERT_SUDUNGDICHVU
    @IDHOSO VARCHAR(10),
    @IDDICHVU VARCHAR(5)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HoSoBenhNhan
        WHERE @IDHOSO = IDHoSo)
	BEGIN
        RAISERROR('INVALID HO SO BENH NHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM DICHVU WHERE IDDICHVU = @IDDICHVU) 
	BEGIN
        RAISERROR('INVALID IDDICHVU', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF EXISTS (SELECT * FROM SuDungDV
        WHERE @IDHOSO = IDHoSo AND IDDICHVU = @IDDICHVU) BEGIN
        RAISERROR('DICHVU DA DUOC SU DUNG', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    DECLARE @TIENDICHVU INT
    SET @TIENDICHVU = (SELECT PhiDichVu FROM DICHVU WHERE IDDICHVU = @IDDICHVU)

    INSERT INTO SuDungDV
    VALUES (@IDDICHVU, @IDHOSO)

    UPDATE HoaDon SET TongTien = TongTien + @TIENDICHVU WHERE IDHoSo = @IDHOSO
COMMIT TRAN
RETURN 0
GO

--delete from SuDungDV
SELECT * FROM SuDungDV
SELECT * FROM HoaDon
EXEC SP_INSERT_SUDUNGDICHVU 'HS01', 'DV01'