use NHAKHOA
go

CREATE OR ALTER PROC SP_INSERT_MEDICINE
	@MATHUOC VARCHAR(10) = NULL OUTPUT, 
    @TENTHUOC NVARCHAR(30),
    @DONVITINH NVARCHAR(10),
    @CHIDINH NVARCHAR(10),
    @SOLUONGTON INT,
    @NGAYHETHAN DATE,
    @DONGIA INT,
    @NGUOIQUANLY VARCHAR(10)
    
AS BEGIN TRAN
	IF @TENTHUOC IS NULL
	BEGIN
        RAISERROR(N'INVALID TENTTHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @DONVITINH != 'GAM' AND @DONVITINH != N'MLÍT'
    BEGIN
        RAISERROR(N'INVALID DONVITINH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @SOLUONGTON < 0 
	BEGIN
        RAISERROR('INVALID SOLUONGTON', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF DATEDIFF(d, @NGAYHETHAN, GETDATE()) > 0
	BEGIN
        RAISERROR('INVALID NGAYHETHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END
	
    IF @DONGIA < 0 
	BEGIN
        RAISERROR('INVALID GIATIEN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF LEFT(@NGUOIQUANLY, 2) != 'AD' 
	BEGIN
        RAISERROR('NGUOIQUANLY MUST BE AN ADMIN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM NhanSu WHERE IDNhanSu = @NGUOIQUANLY) 
	BEGIN
        RAISERROR('INVALID NGUOIQUANLY', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    SELECT @MATHUOC = MATHUOC FROM THUOC
    WHERE MATHUOC = (SELECT MAX(MATHUOC) FROM THUOC)

    SET @MATHUOC = dbo.F_GenerateID('TH', @MATHUOC)

    INSERT INTO THUOC
    VALUES (@MATHUOC, @TENTHUOC, @DONVITINH, @CHIDINH,
        @SOLUONGTON, @NGAYHETHAN, @DONGIA, @NGUOIQUANLY)
    
COMMIT TRAN
RETURN 0
GO

EXEC SP_INSERT_MEDICINE
 null, N'Amoxicillin', N'GAM', N'Sau khi ăn', 100, '2025/12/22', 10000, 'AD01'

EXEC SP_INSERT_MEDICINE
 null, N'Oxaprozin', N'GAM', N'Trước khi ăn', 500, '2026/12/30', 2000, 'AD01'

EXEC SP_INSERT_MEDICINE
 null, N'Decongen', N'GAM', N'Uống sáng', 50, '2026/12/30', 5000, 'AD01'

EXEC SP_INSERT_MEDICINE
 null, N'Paracetamol', N'MLÍT', N'Khi nhức đầu', 150, '2026/05/16', 3000, 'AD01'

EXEC SP_INSERT_MEDICINE
 null, N'Melatonin', N'MLÍT', N'Khi thiếu ngủ', 200, '2026/07/21', 4000, 'AD01'

EXEC SP_INSERT_MEDICINE
 null, N'Tiffy', N'GAM', N'Khi cảm', 40, '2026/09/15', 1000, 'AD01'


 SELECT *
 FROM Thuoc