use NHAKHOA
go

CREATE OR ALTER PROC SP_UPDATE_MEDICINE_CD
	@MATHUOC VARCHAR(10),
    @TENTHUOC NVARCHAR(30),
    @DONVITINH NVARCHAR(10),
    @CHIDINH NVARCHAR(10),
    @SOLUONGTON INT,
    @NGAYHETHAN DATE,
    @DONGIA INT,
    @NGUOIQUANLY VARCHAR(10)
AS SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) 
	BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF @TENTHUOC IS NULL
	BEGIN
        RAISERROR(N'INVALID DONVITINH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @DONVITINH != 'GAM' AND @DONVITINH != N'MLÍT'
    BEGIN
        RAISERROR(N'INVALID DONVITINH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @SOLUONGTON < 0 
	BEGIN
        RAISERROR('INVALID SOLUONGTON', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF DATEDIFF(d, @NGAYHETHAN, GETDATE()) > 0
	BEGIN
        RAISERROR('INVALID NGAYHETHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END
	
	IF @DONGIA < 0 
	BEGIN
        RAISERROR('INVALID GIATIEN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF LEFT(@NGUOIQUANLY, 2) != 'AD' 
	BEGIN
        RAISERROR('NGUOIQUANLY MUST BE AN ADMIN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM NhanSu WHERE IDNhanSu = @NGUOIQUANLY) 
	BEGIN
        RAISERROR('INVALID NGUOIQUANLY', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	WAITFOR DELAY '00:00:05'

    UPDATE THUOC SET TENTHUOC = @TENTHUOC, DVT = @DONVITINH,
        CHIDINH = @CHIDINH, SOLUONGTON = @SOLUONGTON,
        NGAYHETHAN = @NGAYHETHAN, DONGIA = @DONGIA,
        NGUOIQUANLI = @NGUOIQUANLY
    WHERE MATHUOC = @MATHUOC
    
COMMIT TRAN
RETURN 0
GO