USE NHAKHOA
GO
 --SELECT *
 --FROM Thuoc
DECLARE @RS INT
EXEC @RS = SP_UPDATE_MEDICINE_UNR 'TH03', N'Decongen',  N'GAM', N'Uống sáng', 50, '2026/12/30', 5000, 'AD01'
IF @RS = -1
	PRINT N'CẬP NHẬT THẤT BẠI'
ELSE
	PRINT N'CẬP NHẬT THÀNH CÔNG'