use NHAKHOA
go

--TRAN1
CREATE OR ALTER PROC SP_VIEW_LICHHEN_NS
    @IDNHASI VARCHAR(5)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM NhanSu
        WHERE IDNhanSu = @IDNHASI) 
	BEGIN
        RAISERROR('INVALID IDNHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	DECLARE @SOLICHHEN INT
	SELECT @SOLICHHEN = COUNT(*) FROM LICHHEN WHERE NGUOIKHAM = @IDNHASI 
    
	SELECT * FROM LICHHEN WHERE NGUOIKHAM = @IDNHASI
	print(N'Số lượng lịch hẹn đang có: ' + cast(@SOLICHHEN AS VARCHAR(5)))

	WAITFOR DELAY '00:00:10'
	SELECT @SOLICHHEN = COUNT(*) FROM LICHHEN WHERE NGUOIKHAM = @IDNHASI 
    
	SELECT * FROM LICHHEN WHERE NGUOIKHAM = @IDNHASI
	print(N'Số lượng lịch hẹn đang có: ' + cast(@SOLICHHEN AS VARCHAR(5)))

COMMIT TRAN
GO

--TRAN2
CREATE OR ALTER PROC SP_INSERT_LICHHEN
	@IDLICHHEN VARCHAR(10),
    @THOIGIANKHAM DATE,
    @IDKHACHHANG VARCHAR(5),
    @IDNHASI VARCHAR(5),
    @IDNVDATLICH VARCHAR(5) = NULL
AS BEGIN TRAN
	IF DATEDIFF(d, @THOIGIANKHAM, GETDATE()) > 0
	BEGIN
        RAISERROR('THOI GIAN KHONG HOP LE', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM KHACHHANG
					WHERE IDKHACHHANG = @IDKHACHHANG) 
	BEGIN
        RAISERROR('INVALID IDKHACHHANG', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM NhanSu
        WHERE IDNhanSu = @IDNHASI) 
	BEGIN
        RAISERROR('INVALID IDNHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF EXISTS (SELECT * FROM LichHen 
				WHERE ThoiGianKham = @THOIGIANKHAM AND NguoiKham = @IDNHASI AND IDKhachHang = @IDKHACHHANG)
	BEGIN
        RAISERROR('LICH HEN DA TON TAI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @IDNVDATLICH IS NOT NULL AND NOT EXISTS
        (SELECT * FROM NhanSu WHERE IDNhanSu = @IDNVDATLICH) 
	BEGIN
        RAISERROR('INVALID IDNVDATLICH', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM LichNhaSi 
					WHERE ThoiGianTrong = @THOIGIANKHAM AND IDNhaSi = @IDNHASI)
	BEGIN
        RAISERROR('NHASI IS NOT AVAILABLE AT THAT TIME', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    SELECT @IDLICHHEN = IDLICHHEN FROM LICHHEN
    WHERE IDLICHHEN = (SELECT MAX(IDLICHHEN) FROM LICHHEN)

    SET @IDLICHHEN = dbo.F_GenerateID('LH', @IDLICHHEN)

    INSERT INTO LICHHEN
    VALUES (@IDLICHHEN, @THOIGIANKHAM, @IDKHACHHANG, @IDNHASI, @IDNVDATLICH)
COMMIT TRAN
GO