USE NHAKHOA
GO
--TRAN1 
CREATE OR ALTER PROC SP_UPDATE_SUDUNGTHUOC_CYD
    @IDHOSO VARCHAR(10),
    @MATHUOC VARCHAR(5),
    @SOLUONGMOI INT
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HoSoBenhNhan
        WHERE @IDHOSO = IDHoSo)
	BEGIN
        RAISERROR('INVALID HO SO BENH NHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) 
	BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC
        AND SoLuongTon >= @SOLUONGMOI)  
	BEGIN
        RAISERROR('SO LUONG THUOC KHONG DU', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    DECLARE @TIENTHUOCMOI INT
    SET @TIENTHUOCMOI = (SELECT DonGia FROM THUOC WHERE MATHUOC = @MATHUOC) * @SOLUONGMOI

	DECLARE @TIENTHUOCCU INT, @SOLUONGCU INT 
	SET @SOLUONGCU = (SELECT SoLuong FROM SuDungThuoc WHERE IDThuoc = @MATHUOC)
    SET @TIENTHUOCCU = (SELECT DonGia FROM THUOC WHERE MATHUOC = @MATHUOC) * @SOLUONGCU
	
	WAITFOR DELAY '00:00:05'
    UPDATE SuDungThuoc SET SoLuong = @SOLUONGMOI WHERE IDHoSo = @IDHOSO AND IDThuoc = @MATHUOC
	
	WAITFOR DELAY '00:00:05'
    UPDATE HoaDon SET TongTien = TongTien - @TIENTHUOCCU + @TIENTHUOCMOI WHERE IDHoSo = @IDHOSO
	UPDATE THUOC SET SoLuongTon = SoLuongTon + @SOLUONGCU - @SOLUONGMOI WHERE MATHUOC = @MATHUOC
	
COMMIT TRAN
RETURN 0
GO

--TRAN2
CREATE OR ALTER PROC SP_DELETE_SUDUNGTHUOC_CYD_FIX
    @IDHOSO VARCHAR(10),
    @MATHUOC VARCHAR(5)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HoSoBenhNhan
        WHERE @IDHOSO = IDHoSo)
	BEGIN
        RAISERROR('INVALID HO SO BENH NHAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @MATHUOC) 
	BEGIN
        RAISERROR('INVALID MATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END
	
	WAITFOR DELAY '00:00:05'

	DECLARE @SOLUONG INT 
	SET @SOLUONG = (SELECT SoLuong FROM SuDungThuoc WHERE IDThuoc = @MATHUOC)

    DECLARE @TIENTHUOC INT
    SET @TIENTHUOC = (SELECT DonGia FROM THUOC WHERE MATHUOC = @MATHUOC) * @SOLUONG
	DELETE FROM SuDungThuoc WHERE IDHoSo = @IDHOSO AND IDThuoc = @MATHUOC
	
    WAITFOR DELAY '00:00:05'
	UPDATE HoaDon SET TongTien = TongTien - @TIENTHUOC WHERE IDHoSo = @IDHOSO
	
	UPDATE THUOC SET SoLuongTon = SoLuongTon + @SOLUONG WHERE MATHUOC = @MATHUOC
COMMIT TRAN
RETURN 0
GO