USE NHAKHOA
GO


CREATE OR ALTER PROC SP_UPDATE_HOSOBENHNHAN_LU
	@IDHOSO VARCHAR(10),
    @SONGAYDOI INT
AS BEGIN TRAN
    IF @SONGAYDOI = 0
	BEGIN
        RAISERROR('NGAY DOI PHAI KHAC 0', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	IF NOT EXISTS (SELECT * FROM HoSoBenhNhan WHERE IDHoSo = @IDHOSO)
	BEGIN
        RAISERROR('HO SO KHONG TON TAI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

	DECLARE @NGAYCU DATE
	SELECT @NGAYCU = ThoiGianKham FROM HoSoBenhNhan WHERE IDHoSo = @IDHOSO

	DECLARE @NGAYMOI DATE 
	set @NGAYMOI = DATEADD(DAY, @SONGAYDOI, @NGAYCU)


    WAITFOR DELAY '00:00:05'

    UPDATE HoSoBenhNhan SET ThoiGianKham = @NGAYMOI WHERE IDHoSo = @IDHOSO
	IF @@ERROR <> 0
	BEGIN
		PRINT N'LOI HẸ THỐNG'
		RETURN
	END
COMMIT TRAN
GO