USE NHAKHOA
GO

--SELECT * FROM LichHen WHERE IDLichHen = 'LH05'
--LOST UPDATE
EXEC SP_UPDATE_HOSOBENHNHAN_LU 'HS04', -4

SELECT * FROM HoSoBenhNhan WHERE IDHoSo = 'HS04'

--FIX
EXEC SP_UPDATE_HOSOBENHNHAN_LU_FIX 'HS04', -4

SELECT * FROM HoSoBenhNhan WHERE IDHoSo = 'HS04'